layout_spectrum: 0.235768
color:
  saturation: 0.06869829
  lightness: 0.6612376
  brandStrength: 0.4978518
  brandColors:
    - '#F7E1D4'
    - '#050706'
    - '#57ACCD'
    - '#1A7B8B'
    - '#AC1506'
  rhythmicContrast: 0.02615724
typography_spectrum: 0.1219119
name: 'aimadzakaria '
