collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.06176154
color:
  saturation: 0.06869829
  brandStrength: 0.4978518
  rhythmicContrast: 0.02615724
  brandColors:
    - '#F7E1D4'
    - '#050706'
    - '#57ACCD'
    - '#1A7B8B'
    - '#AC1506'
  lightness: 0.6612376
layout_spectrum: 0.235768
name: 'aimadzakaria '
